driver_path: 'chromedriver/chromedriver.exe'
base_url: 'http://localhost/'
wait_time: 10
headless: True
sql_check: True
mysql_host: 'localhost'
mysql_port: 3306
mysql_user: 'admin'
mysql_pwd: 'Admin_123'
mysql_db: 'rjgcdb'